/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(uart_frame, uart_frame, AUTO)


PB_BIND(uart_frame_uart_command, uart_frame_uart_command, AUTO)






